# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/agent/critic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/agent/critic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#moleculeforge/v1/agent/critic.proto\x12\x16moleculeforge.v1.agent\"\xc3\x02\n\x0e\x43riticFeedback\x12\x17\n\x0fmolecule_smiles\x18\x01 \x01(\t\x12\x0f\n\x07rule_id\x18\x02 \x01(\t\x12\x11\n\trule_name\x18\x03 \x01(\t\x12\x0f\n\x07verdict\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\x01\x12\x11\n\treasoning\x18\x06 \x01(\t\x12\x1c\n\x14violated_constraints\x18\x07 \x03(\t\x12\x1d\n\x15satisfied_constraints\x18\x08 \x03(\t\x12O\n\rmetric_values\x18\t \x03(\x0b\x32\x38.moleculeforge.v1.agent.CriticFeedback.MetricValuesEntry\x1a\x33\n\x11MetricValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\xf8\x02\n\x11\x43riticBatchResult\x12\x17\n\x0fmolecule_smiles\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12<\n\x0crule_results\x18\x03 \x03(\x0b\x32&.moleculeforge.v1.agent.CriticFeedback\x12\x12\n\nall_passed\x18\x04 \x01(\x08\x12\x17\n\x0frules_evaluated\x18\x05 \x01(\x05\x12\x14\n\x0crules_passed\x18\x06 \x01(\x05\x12\x17\n\x0f\x61ggregate_score\x18\x07 \x01(\x01\x12\x14\n\x0c\x63\x61ndidate_id\x18\x08 \x01(\t\x12\x1c\n\x0f\x63\x61ndidate_index\x18\t \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x10\x63\x61nonical_smiles\x18\n \x01(\t\x12\x0e\n\x06run_id\x18\x0b \x01(\t\x12\x12\n\nrequest_id\x18\x0c \x01(\t\x12\x16\n\x0eschema_version\x18\r \x01(\tB\x12\n\x10_candidate_index2\xdd\x01\n\rCriticService\x12`\n\x08\x45valuate\x12).moleculeforge.v1.agent.CriticBatchResult\x1a).moleculeforge.v1.agent.CriticBatchResult\x12j\n\x0e\x45valuateStream\x12).moleculeforge.v1.agent.CriticBatchResult\x1a).moleculeforge.v1.agent.CriticBatchResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.agent.critic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CRITICFEEDBACK_METRICVALUESENTRY']._loaded_options = None
  _globals['_CRITICFEEDBACK_METRICVALUESENTRY']._serialized_options = b'8\001'
  _globals['_CRITICFEEDBACK']._serialized_start=64
  _globals['_CRITICFEEDBACK']._serialized_end=387
  _globals['_CRITICFEEDBACK_METRICVALUESENTRY']._serialized_start=336
  _globals['_CRITICFEEDBACK_METRICVALUESENTRY']._serialized_end=387
  _globals['_CRITICBATCHRESULT']._serialized_start=390
  _globals['_CRITICBATCHRESULT']._serialized_end=766
  _globals['_CRITICSERVICE']._serialized_start=769
  _globals['_CRITICSERVICE']._serialized_end=990
# @@protoc_insertion_point(module_scope)
