# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/agent/orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/agent/orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)moleculeforge/v1/agent/orchestrator.proto\x12\x16moleculeforge.v1.agent\"\xb9\x01\n\rNL2ObjRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x1f\n\x17natural_language_prompt\x18\x02 \x01(\t\x12\x43\n\x07\x63ontext\x18\x03 \x03(\x0b\x32\x32.moleculeforge.v1.agent.NL2ObjRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"{\n\rObjectiveSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tdirection\x18\x03 \x01(\t\x12\x14\n\x0ctarget_value\x18\x04 \x01(\x01\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12\x10\n\x08priority\x18\x06 \x01(\t\"\xb2\x02\n\x0eNL2ObjResponse\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x10\n\x08nl_query\x18\x02 \x01(\t\x12\x39\n\nobjectives\x18\x03 \x03(\x0b\x32%.moleculeforge.v1.agent.ObjectiveSpec\x12L\n\x0b\x63onstraints\x18\x04 \x03(\x0b\x32\x37.moleculeforge.v1.agent.NL2ObjResponse.ConstraintsEntry\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x12\x15\n\rparsed_intent\x18\x06 \x01(\t\x12\x12\n\nelapsed_ms\x18\x07 \x01(\x03\x1a\x32\n\x10\x43onstraintsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"v\n\x13NL2ObjRefineRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x39\n\nobjectives\x18\x02 \x03(\x0b\x32%.moleculeforge.v1.agent.ObjectiveSpec\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x03 \x01(\t\"\x7f\n\x14NL2ObjRefineResponse\x12\x39\n\nobjectives\x18\x01 \x03(\x0b\x32%.moleculeforge.v1.agent.ObjectiveSpec\x12\x18\n\x10\x66\x65\x65\x64\x62\x61\x63k_applied\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x32\xcc\x01\n\rNL2ObjService\x12V\n\x05Parse\x12%.moleculeforge.v1.agent.NL2ObjRequest\x1a&.moleculeforge.v1.agent.NL2ObjResponse\x12\x63\n\x06Refine\x12+.moleculeforge.v1.agent.NL2ObjRefineRequest\x1a,.moleculeforge.v1.agent.NL2ObjRefineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.agent.orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NL2OBJREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_NL2OBJREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_NL2OBJRESPONSE_CONSTRAINTSENTRY']._loaded_options = None
  _globals['_NL2OBJRESPONSE_CONSTRAINTSENTRY']._serialized_options = b'8\001'
  _globals['_NL2OBJREQUEST']._serialized_start=70
  _globals['_NL2OBJREQUEST']._serialized_end=255
  _globals['_NL2OBJREQUEST_CONTEXTENTRY']._serialized_start=209
  _globals['_NL2OBJREQUEST_CONTEXTENTRY']._serialized_end=255
  _globals['_OBJECTIVESPEC']._serialized_start=257
  _globals['_OBJECTIVESPEC']._serialized_end=380
  _globals['_NL2OBJRESPONSE']._serialized_start=383
  _globals['_NL2OBJRESPONSE']._serialized_end=689
  _globals['_NL2OBJRESPONSE_CONSTRAINTSENTRY']._serialized_start=639
  _globals['_NL2OBJRESPONSE_CONSTRAINTSENTRY']._serialized_end=689
  _globals['_NL2OBJREFINEREQUEST']._serialized_start=691
  _globals['_NL2OBJREFINEREQUEST']._serialized_end=809
  _globals['_NL2OBJREFINERESPONSE']._serialized_start=811
  _globals['_NL2OBJREFINERESPONSE']._serialized_end=938
  _globals['_NL2OBJSERVICE']._serialized_start=941
  _globals['_NL2OBJSERVICE']._serialized_end=1145
# @@protoc_insertion_point(module_scope)
