# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/agent/orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/agent/orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)moleculeforge/v1/agent/orchestrator.proto\x12\x16moleculeforge.v1.agent\"\xe6\x01\n\x11OrchestratorState\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63urrent_node\x18\x03 \x01(\t\x12\x13\n\x0b\x63ycle_count\x18\x04 \x01(\x05\x12\x12\n\nmax_cycles\x18\x05 \x01(\x05\x12\x15\n\rvisited_nodes\x18\x06 \x03(\t\x12\x17\n\x0fpending_actions\x18\x07 \x03(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\x15\n\rstarted_at_ns\x18\t \x01(\x03\x12\x17\n\x0flast_updated_ns\x18\n \x01(\x03\"\xb9\x01\n\rNL2ObjRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x1f\n\x17natural_language_prompt\x18\x02 \x01(\t\x12\x43\n\x07\x63ontext\x18\x03 \x03(\x0b\x32\x32.moleculeforge.v1.agent.NL2ObjRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf3\x01\n\x15OrchestrationDecision\x12\x10\n\x08\x64\x65\x63ision\x18\x01 \x01(\t\x12\x11\n\treasoning\x18\x02 \x01(\t\x12\x13\n\x0bnext_agents\x18\x03 \x03(\t\x12\x1a\n\x12target_molecule_id\x18\x04 \x01(\t\x12Q\n\nparameters\x18\x05 \x03(\x0b\x32=.moleculeforge.v1.agent.OrchestrationDecision.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.agent.orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NL2OBJREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_NL2OBJREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_ORCHESTRATIONDECISION_PARAMETERSENTRY']._loaded_options = None
  _globals['_ORCHESTRATIONDECISION_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_ORCHESTRATORSTATE']._serialized_start=70
  _globals['_ORCHESTRATORSTATE']._serialized_end=300
  _globals['_NL2OBJREQUEST']._serialized_start=303
  _globals['_NL2OBJREQUEST']._serialized_end=488
  _globals['_NL2OBJREQUEST_CONTEXTENTRY']._serialized_start=442
  _globals['_NL2OBJREQUEST_CONTEXTENTRY']._serialized_end=488
  _globals['_ORCHESTRATIONDECISION']._serialized_start=491
  _globals['_ORCHESTRATIONDECISION']._serialized_end=734
  _globals['_ORCHESTRATIONDECISION_PARAMETERSENTRY']._serialized_start=685
  _globals['_ORCHESTRATIONDECISION_PARAMETERSENTRY']._serialized_end=734
# @@protoc_insertion_point(module_scope)
