# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mf_core.proto_gen.moleculeforge.v1.generator import router_pb2 as moleculeforge_dot_v1_dot_generator_dot_router__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in moleculeforge/v1/generator/router_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeneratorRouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Route = channel.unary_unary(
                '/moleculeforge.v1.generator.GeneratorRouterService/Route',
                request_serializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterResponse.FromString,
                _registered_method=True)
        self.RunProxylessSearch = channel.unary_unary(
                '/moleculeforge.v1.generator.GeneratorRouterService/RunProxylessSearch',
                request_serializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterProxylessSearchRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterProxylessSearchResponse.FromString,
                _registered_method=True)
        self.SubmitFeedback = channel.unary_unary(
                '/moleculeforge.v1.generator.GeneratorRouterService/SubmitFeedback',
                request_serializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterFeedbackRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterFeedbackResponse.FromString,
                _registered_method=True)
        self.GetWeights = channel.unary_unary(
                '/moleculeforge.v1.generator.GeneratorRouterService/GetWeights',
                request_serializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterWeightsResponse.FromString,
                _registered_method=True)


class GeneratorRouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Route(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def RunProxylessSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def SubmitFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def GetWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')


def add_GeneratorRouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterResponse.SerializeToString,
            ),
            'RunProxylessSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.RunProxylessSearch,
                    request_deserializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterProxylessSearchRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterProxylessSearchResponse.SerializeToString,
            ),
            'SubmitFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFeedback,
                    request_deserializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterFeedbackRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterFeedbackResponse.SerializeToString,
            ),
            'GetWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeights,
                    request_deserializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterWeightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moleculeforge.v1.generator.GeneratorRouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moleculeforge.v1.generator.GeneratorRouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeneratorRouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.generator.GeneratorRouterService/Route',
            moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterRequest.SerializeToString,
            moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunProxylessSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.generator.GeneratorRouterService/RunProxylessSearch',
            moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterProxylessSearchRequest.SerializeToString,
            moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterProxylessSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.generator.GeneratorRouterService/SubmitFeedback',
            moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterFeedbackRequest.SerializeToString,
            moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.generator.GeneratorRouterService/GetWeights',
            moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterRequest.SerializeToString,
            moleculeforge_dot_v1_dot_generator_dot_router__pb2.RouterWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
