# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/generator/router.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/generator/router.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'moleculeforge/v1/generator/router.proto\x12\x1amoleculeforge.v1.generator\"|\n\rRouterRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63ig\x18\x02 \x01(\x0c\x12\x19\n\x11generator_weights\x18\x03 \x03(\x01\x12\x1d\n\x15generator_performance\x18\x04 \x03(\x01\x12\x10\n\x08n_select\x18\x05 \x01(\x05\"t\n\x0eRouterResponse\x12\x1b\n\x13selected_generators\x18\x01 \x03(\t\x12\x19\n\x11selection_weights\x18\x02 \x03(\x01\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x18\n\x10\x65xpected_rewards\x18\x04 \x03(\x01\x32x\n\x16GeneratorRouterService\x12^\n\x05Route\x12).moleculeforge.v1.generator.RouterRequest\x1a*.moleculeforge.v1.generator.RouterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.generator.router_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTERREQUEST']._serialized_start=71
  _globals['_ROUTERREQUEST']._serialized_end=195
  _globals['_ROUTERRESPONSE']._serialized_start=197
  _globals['_ROUTERRESPONSE']._serialized_end=313
  _globals['_GENERATORROUTERSERVICE']._serialized_start=315
  _globals['_GENERATORROUTERSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
