# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/generator/router.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/generator/router.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'moleculeforge/v1/generator/router.proto\x12\x1amoleculeforge.v1.generator\"\x9f\x02\n\rRouterRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63ig\x18\x02 \x01(\x0c\x12\x19\n\x11generator_weights\x18\x03 \x03(\x01\x12\x1d\n\x15generator_performance\x18\x04 \x03(\x01\x12\x10\n\x08n_select\x18\x05 \x01(\x05\x12\x0c\n\x04hciv\x18\x06 \x03(\x01\x12\x15\n\rtarget_family\x18\x07 \x01(\t\x12\r\n\x05stage\x18\x08 \x01(\t\x12\x15\n\rdata_richness\x18\t \x01(\x01\x12\x16\n\x0enovelty_demand\x18\n \x01(\x01\x12\x14\n\x0cmulti_target\x18\x0b \x01(\x08\x12\x15\n\rsa_constraint\x18\x0c \x01(\x01\x12\x11\n\tn_samples\x18\r \x01(\x05\"t\n\x0eRouterResponse\x12\x1b\n\x13selected_generators\x18\x01 \x03(\t\x12\x19\n\x11selection_weights\x18\x02 \x03(\x01\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x18\n\x10\x65xpected_rewards\x18\x04 \x03(\x01\"\x9a\x01\n\x1cRouterProxylessSearchRequest\x12\x1b\n\x13reward_batches_json\x18\x01 \x01(\t\x12\x1c\n\x14generator_costs_json\x18\x02 \x01(\t\x12\x13\n\x0b\x63ost_weight\x18\x03 \x01(\x01\x12\x15\n\rlearning_rate\x18\x04 \x01(\x01\x12\x13\n\x0btemperature\x18\x05 \x01(\x01\"\x9c\x01\n\x1dRouterProxylessSearchResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\x17\n\x0fgenerator_names\x18\x03 \x03(\t\x12\"\n\x1a\x61rchitecture_probabilities\x18\x04 \x03(\x01\x12\x13\n\x0bround_count\x18\x05 \x01(\x05\x32\x84\x02\n\x16GeneratorRouterService\x12^\n\x05Route\x12).moleculeforge.v1.generator.RouterRequest\x1a*.moleculeforge.v1.generator.RouterResponse\x12\x89\x01\n\x12RunProxylessSearch\x12\x38.moleculeforge.v1.generator.RouterProxylessSearchRequest\x1a\x39.moleculeforge.v1.generator.RouterProxylessSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.generator.router_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTERREQUEST']._serialized_start=72
  _globals['_ROUTERREQUEST']._serialized_end=359
  _globals['_ROUTERRESPONSE']._serialized_start=361
  _globals['_ROUTERRESPONSE']._serialized_end=477
  _globals['_ROUTERPROXYLESSSEARCHREQUEST']._serialized_start=480
  _globals['_ROUTERPROXYLESSSEARCHREQUEST']._serialized_end=634
  _globals['_ROUTERPROXYLESSSEARCHRESPONSE']._serialized_start=637
  _globals['_ROUTERPROXYLESSSEARCHRESPONSE']._serialized_end=793
  _globals['_GENERATORROUTERSERVICE']._serialized_start=796
  _globals['_GENERATORROUTERSERVICE']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
