# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/core/humu.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/core/humu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n moleculeforge/v1/core/humu.proto\x12\x15moleculeforge.v1.core\"w\n\x04HCIV\x12\x13\n\x0b\x63oordinates\x18\x01 \x03(\x02\x12\x11\n\tcurvature\x18\x02 \x01(\x01\x12\x17\n\x0fmolecule_smiles\x18\x03 \x01(\t\x12\x1b\n\x0eparent_hciv_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_parent_hciv_id\"\xcb\x01\n\nIntentCone\x12\x0c\n\x04\x61xis\x18\x01 \x03(\x02\x12\x12\n\nhalf_angle\x18\x02 \x01(\x01\x12\x11\n\tcurvature\x18\x03 \x01(\x01\x12P\n\x10property_weights\x18\x04 \x03(\x0b\x32\x36.moleculeforge.v1.core.IntentCone.PropertyWeightsEntry\x1a\x36\n\x14PropertyWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"`\n\tHCIVBatch\x12/\n\nembeddings\x18\x01 \x03(\x0b\x32\x1b.moleculeforge.v1.core.HCIV\x12\x15\n\x08\x62\x61tch_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_batch_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.core.humu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTENTCONE_PROPERTYWEIGHTSENTRY']._loaded_options = None
  _globals['_INTENTCONE_PROPERTYWEIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_HCIV']._serialized_start=59
  _globals['_HCIV']._serialized_end=178
  _globals['_INTENTCONE']._serialized_start=181
  _globals['_INTENTCONE']._serialized_end=384
  _globals['_INTENTCONE_PROPERTYWEIGHTSENTRY']._serialized_start=330
  _globals['_INTENTCONE_PROPERTYWEIGHTSENTRY']._serialized_end=384
  _globals['_HCIVBATCH']._serialized_start=386
  _globals['_HCIVBATCH']._serialized_end=482
# @@protoc_insertion_point(module_scope)
