# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/core/ssp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/core/ssp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmoleculeforge/v1/core/ssp.proto\x12\x15moleculeforge.v1.core\"\x98\x02\n\rSynthesisStep\x12\x13\n\x0bstep_number\x18\x01 \x01(\x05\x12\x11\n\toperation\x18\x02 \x01(\t\x12H\n\nparameters\x18\x03 \x03(\x0b\x32\x34.moleculeforge.v1.core.SynthesisStep.ParametersEntry\x12\x10\n\x08reagents\x18\x04 \x03(\t\x12\x0f\n\x07solvent\x18\x05 \x01(\t\x12\x15\n\rtemperature_c\x18\x06 \x01(\x01\x12\x14\n\x0c\x64uration_min\x18\x07 \x01(\x05\x12\x12\n\natmosphere\x18\x08 \x01(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x93\x02\n\x03SSP\x12\x0e\n\x06ssp_id\x18\x01 \x01(\t\x12\x17\n\x0fmolecule_smiles\x18\x02 \x01(\t\x12\x33\n\x05steps\x18\x03 \x03(\x0b\x32$.moleculeforge.v1.core.SynthesisStep\x12\x14\n\x0cgenerated_by\x18\x04 \x01(\t\x12\x17\n\x0fpredicted_yield\x18\x05 \x01(\x01\x12\x12\n\nxdl_output\x18\x06 \x01(\t\x12:\n\x08metadata\x18\x07 \x03(\x0b\x32(.moleculeforge.v1.core.SSP.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.core.ssp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESISSTEP_PARAMETERSENTRY']._loaded_options = None
  _globals['_SYNTHESISSTEP_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_SSP_METADATAENTRY']._loaded_options = None
  _globals['_SSP_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SYNTHESISSTEP']._serialized_start=59
  _globals['_SYNTHESISSTEP']._serialized_end=339
  _globals['_SYNTHESISSTEP_PARAMETERSENTRY']._serialized_start=290
  _globals['_SYNTHESISSTEP_PARAMETERSENTRY']._serialized_end=339
  _globals['_SSP']._serialized_start=342
  _globals['_SSP']._serialized_end=617
  _globals['_SSP_METADATAENTRY']._serialized_start=570
  _globals['_SSP_METADATAENTRY']._serialized_end=617
# @@protoc_insertion_point(module_scope)
