# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mf_core.proto_gen.moleculeforge.v1.oracle import boltz2_pb2 as moleculeforge_dot_v1_dot_oracle_dot_boltz2__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in moleculeforge/v1/oracle/boltz2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Boltz2ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictAffinity = channel.unary_unary(
                '/moleculeforge.v1.oracle.Boltz2Service/PredictAffinity',
                request_serializer=moleculeforge_dot_v1_dot_oracle_dot_boltz2__pb2.Boltz2BatchRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_oracle_dot_boltz2__pb2.Boltz2BatchResponse.FromString,
                _registered_method=True)


class Boltz2ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictAffinity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')


def add_Boltz2ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictAffinity': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictAffinity,
                    request_deserializer=moleculeforge_dot_v1_dot_oracle_dot_boltz2__pb2.Boltz2BatchRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_oracle_dot_boltz2__pb2.Boltz2BatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moleculeforge.v1.oracle.Boltz2Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moleculeforge.v1.oracle.Boltz2Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Boltz2Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictAffinity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.oracle.Boltz2Service/PredictAffinity',
            moleculeforge_dot_v1_dot_oracle_dot_boltz2__pb2.Boltz2BatchRequest.SerializeToString,
            moleculeforge_dot_v1_dot_oracle_dot_boltz2__pb2.Boltz2BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
