# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/core/audit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/core/audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!moleculeforge/v1/core/audit.proto\x12\x15moleculeforge.v1.core\"\x9e\x02\n\nAuditEvent\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\r\n\x05\x61\x63tor\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\x0e\n\x06target\x18\x06 \x01(\t\x12\x0f\n\x07outcome\x18\x07 \x01(\t\x12\x11\n\tsignature\x18\x08 \x01(\x0c\x12\x15\n\rsignature_uri\x18\t \x01(\t\x12?\n\x07lineage\x18\n \x03(\x0b\x32..moleculeforge.v1.core.AuditEvent.LineageEntry\x1a.\n\x0cLineageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"}\n\nAuditQuery\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x15\n\rstart_time_ns\x18\x03 \x01(\x03\x12\x13\n\x0b\x65nd_time_ns\x18\x04 \x01(\x03\x12\x0e\n\x06\x61\x63tors\x18\x05 \x03(\t\x12\r\n\x05limit\x18\x06 \x01(\x05\"\x80\x01\n\x0b\x41uditReport\x12\x31\n\x06\x65vents\x18\x01 \x03(\x0b\x32!.moleculeforge.v1.core.AuditEvent\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x12\x10\n\x08has_more\x18\x03 \x01(\x08\x12\x17\n\x0fnext_page_token\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.core.audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDITEVENT_LINEAGEENTRY']._loaded_options = None
  _globals['_AUDITEVENT_LINEAGEENTRY']._serialized_options = b'8\001'
  _globals['_AUDITEVENT']._serialized_start=61
  _globals['_AUDITEVENT']._serialized_end=347
  _globals['_AUDITEVENT_LINEAGEENTRY']._serialized_start=301
  _globals['_AUDITEVENT_LINEAGEENTRY']._serialized_end=347
  _globals['_AUDITQUERY']._serialized_start=349
  _globals['_AUDITQUERY']._serialized_end=474
  _globals['_AUDITREPORT']._serialized_start=477
  _globals['_AUDITREPORT']._serialized_end=605
# @@protoc_insertion_point(module_scope)
