# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/core/cig.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/core/cig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmoleculeforge/v1/core/cig.proto\x12\x15moleculeforge.v1.core\"\xfa\x01\n\rObjectiveNode\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x32\n\x04type\x18\x03 \x01(\x0e\x32$.moleculeforge.v1.core.ObjectiveType\x12\x14\n\x0ctarget_value\x18\x04 \x01(\x01\x12\x17\n\ntarget_min\x18\x05 \x01(\x01H\x00\x88\x01\x01\x12\x17\n\ntarget_max\x18\x06 \x01(\x01H\x01\x88\x01\x01\x12\x10\n\x08property\x18\x07 \x01(\t\x12\x0e\n\x06weight\x18\x08 \x01(\x01\x12\x13\n\x0bpareto_tier\x18\t \x01(\x05\x42\r\n\x0b_target_minB\r\n\x0b_target_max\"Y\n\rObjectiveEdge\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\x10\n\x08relation\x18\x03 \x01(\t\x12\x10\n\x08strength\x18\x04 \x01(\x01\"\x92\x02\n\x03\x43IG\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x38\n\nobjectives\x18\x02 \x03(\x0b\x32$.moleculeforge.v1.core.ObjectiveNode\x12\x33\n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32$.moleculeforge.v1.core.ObjectiveEdge\x12@\n\x0b\x63onstraints\x18\x04 \x03(\x0b\x32+.moleculeforge.v1.core.CIG.ConstraintsEntry\x12\x12\n\ncreated_by\x18\x05 \x01(\t\x1a\x32\n\x10\x43onstraintsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*m\n\rObjectiveType\x12\x1e\n\x1aOBJECTIVE_TYPE_UNSPECIFIED\x10\x00\x12\x0c\n\x08MAXIMIZE\x10\x01\x12\x0c\n\x08MINIMIZE\x10\x02\x12\x10\n\x0cTARGET_RANGE\x10\x03\x12\x0e\n\nCONSTRAINT\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.core.cig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CIG_CONSTRAINTSENTRY']._loaded_options = None
  _globals['_CIG_CONSTRAINTSENTRY']._serialized_options = b'8\001'
  _globals['_OBJECTIVETYPE']._serialized_start=679
  _globals['_OBJECTIVETYPE']._serialized_end=788
  _globals['_OBJECTIVENODE']._serialized_start=59
  _globals['_OBJECTIVENODE']._serialized_end=309
  _globals['_OBJECTIVEEDGE']._serialized_start=311
  _globals['_OBJECTIVEEDGE']._serialized_end=400
  _globals['_CIG']._serialized_start=403
  _globals['_CIG']._serialized_end=677
  _globals['_CIG_CONSTRAINTSENTRY']._serialized_start=627
  _globals['_CIG_CONSTRAINTSENTRY']._serialized_end=677
# @@protoc_insertion_point(module_scope)
