# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/core/crg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/core/crg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmoleculeforge/v1/core/crg.proto\x12\x15moleculeforge.v1.core\"\x9e\x01\n\x06\x42\x65lief\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x11\n\tpredicate\x18\x03 \x01(\t\x12\x0e\n\x06object\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x12\x14\n\x0c\x65vidence_ids\x18\x06 \x03(\t\x12\x14\n\x0csource_agent\x18\x07 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x08 \x01(\x03\"_\n\x07\x43RGEdge\x12\x18\n\x10source_belief_id\x18\x01 \x01(\t\x12\x18\n\x10target_belief_id\x18\x02 \x01(\t\x12\x10\n\x08relation\x18\x03 \x01(\t\x12\x0e\n\x06weight\x18\x04 \x01(\x01\"\xa0\x01\n\x03\x43RG\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12.\n\x07\x62\x65liefs\x18\x02 \x03(\x0b\x32\x1d.moleculeforge.v1.core.Belief\x12-\n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32\x1e.moleculeforge.v1.core.CRGEdge\x12\x0f\n\x07version\x18\x04 \x01(\x05\x12\x15\n\rprovenance_id\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.core.crg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BELIEF']._serialized_start=59
  _globals['_BELIEF']._serialized_end=217
  _globals['_CRGEDGE']._serialized_start=219
  _globals['_CRGEDGE']._serialized_end=314
  _globals['_CRG']._serialized_start=317
  _globals['_CRG']._serialized_end=477
# @@protoc_insertion_point(module_scope)
