# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/core/molecule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/core/molecule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$moleculeforge/v1/core/molecule.proto\x12\x15moleculeforge.v1.core\"\x85\x01\n\x13MolecularProperties\x12\n\n\x02mw\x18\x01 \x01(\x01\x12\x0c\n\x04logp\x18\x02 \x01(\x01\x12\x0b\n\x03hbd\x18\x03 \x01(\x01\x12\x0b\n\x03hba\x18\x04 \x01(\x01\x12\x0c\n\x04tpsa\x18\x05 \x01(\x01\x12\x0b\n\x03qed\x18\x06 \x01(\x01\x12\x10\n\x08sa_score\x18\x07 \x01(\x01\x12\r\n\x05\x65\x63\x66p4\x18\x08 \x01(\x0c\"\xb5\x02\n\x08Molecule\x12\x0e\n\x06smiles\x18\x01 \x01(\t\x12>\n\nproperties\x18\x02 \x01(\x0b\x32*.moleculeforge.v1.core.MolecularProperties\x12\x11\n\tinchi_key\x18\x03 \x01(\t\x12\x16\n\tsdf_bytes\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x12\x1b\n\x0ehumu_embedding\x18\x05 \x01(\x0cH\x01\x88\x01\x01\x12?\n\x08metadata\x18\x06 \x03(\x0b\x32-.moleculeforge.v1.core.Molecule.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0c\n\n_sdf_bytesB\x11\n\x0f_humu_embedding\"g\n\rMoleculeBatch\x12\x32\n\tmolecules\x18\x01 \x03(\x0b\x32\x1f.moleculeforge.v1.core.Molecule\x12\x15\n\x08\x62\x61tch_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_batch_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.core.molecule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOLECULE_METADATAENTRY']._loaded_options = None
  _globals['_MOLECULE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_MOLECULARPROPERTIES']._serialized_start=64
  _globals['_MOLECULARPROPERTIES']._serialized_end=197
  _globals['_MOLECULE']._serialized_start=200
  _globals['_MOLECULE']._serialized_end=509
  _globals['_MOLECULE_METADATAENTRY']._serialized_start=429
  _globals['_MOLECULE_METADATAENTRY']._serialized_end=476
  _globals['_MOLECULEBATCH']._serialized_start=511
  _globals['_MOLECULEBATCH']._serialized_end=614
# @@protoc_insertion_point(module_scope)
