# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/core/pareto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/core/pareto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"moleculeforge/v1/core/pareto.proto\x12\x15moleculeforge.v1.core\"\x96\x02\n\x0bParetoPoint\x12\x17\n\x0fmolecule_smiles\x18\x01 \x01(\t\x12\x18\n\x10objective_values\x18\x02 \x03(\x01\x12\x13\n\x0bpareto_tier\x18\x03 \x01(\x05\x12\x1b\n\x0ehumu_embedding\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x12U\n\x12\x61\x64\x64itional_metrics\x18\x05 \x03(\x0b\x32\x39.moleculeforge.v1.core.ParetoPoint.AdditionalMetricsEntry\x1a\x38\n\x16\x41\x64\x64itionalMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x42\x11\n\x0f_humu_embedding\"\x99\x01\n\x0eParetoFrontier\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x32\n\x06points\x18\x02 \x03(\x0b\x32\".moleculeforge.v1.core.ParetoPoint\x12\x11\n\titeration\x18\x03 \x01(\x03\x12\x13\n\x0bhypervolume\x18\x04 \x01(\x01\x12\x17\n\x0freference_point\x18\x05 \x03(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.core.pareto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARETOPOINT_ADDITIONALMETRICSENTRY']._loaded_options = None
  _globals['_PARETOPOINT_ADDITIONALMETRICSENTRY']._serialized_options = b'8\001'
  _globals['_PARETOPOINT']._serialized_start=62
  _globals['_PARETOPOINT']._serialized_end=340
  _globals['_PARETOPOINT_ADDITIONALMETRICSENTRY']._serialized_start=265
  _globals['_PARETOPOINT_ADDITIONALMETRICSENTRY']._serialized_end=321
  _globals['_PARETOFRONTIER']._serialized_start=343
  _globals['_PARETOFRONTIER']._serialized_end=496
# @@protoc_insertion_point(module_scope)
