# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mf_core.proto_gen.moleculeforge.v1.generator import generator_pb2 as moleculeforge_dot_v1_dot_generator_dot_generator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in moleculeforge/v1/generator/generator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeneratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/moleculeforge.v1.generator.GeneratorService/Generate',
                request_serializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GenerateStream = channel.stream_stream(
                '/moleculeforge.v1.generator.GeneratorService/GenerateStream',
                request_serializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.BatchGenerate = channel.stream_stream(
                '/moleculeforge.v1.generator.GeneratorService/BatchGenerate',
                request_serializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/moleculeforge.v1.generator.GeneratorService/Info',
                request_serializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GeneratorInfo.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GeneratorInfo.FromString,
                _registered_method=True)


class GeneratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def GenerateStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def BatchGenerate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')


def add_GeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.SerializeToString,
            ),
            'GenerateStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.SerializeToString,
            ),
            'BatchGenerate': grpc.stream_stream_rpc_method_handler(
                    servicer.BatchGenerate,
                    request_deserializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GeneratorInfo.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GeneratorInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moleculeforge.v1.generator.GeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moleculeforge.v1.generator.GeneratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeneratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.generator.GeneratorService/Generate',
            moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.SerializeToString,
            moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/moleculeforge.v1.generator.GeneratorService/GenerateStream',
            moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.SerializeToString,
            moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGenerate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/moleculeforge.v1.generator.GeneratorService/BatchGenerate',
            moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateRequest.SerializeToString,
            moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.generator.GeneratorService/Info',
            moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GeneratorInfo.SerializeToString,
            moleculeforge_dot_v1_dot_generator_dot_generator__pb2.GeneratorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
