# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/oracle/boltz2.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/oracle/boltz2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$moleculeforge/v1/oracle/boltz2.proto\x12\x17moleculeforge.v1.oracle\"\xc9\x01\n\x15\x42oltz2BindingAffinity\x12\x16\n\x0eprotein_pdb_id\x18\x01 \x01(\t\x12\x15\n\rligand_smiles\x18\x02 \x01(\t\x12\x18\n\x10\x64\x65lta_g_kcal_mol\x18\x03 \x01(\x01\x12\x13\n\x0buncertainty\x18\x04 \x01(\x01\x12\r\n\x05ki_nm\x18\x05 \x01(\x01\x12\x15\n\rensemble_size\x18\x06 \x01(\x05\x12\x15\n\rper_member_dg\x18\x07 \x03(\x01\x12\x15\n\rmodel_version\x18\x08 \x01(\t\"\x8c\x01\n\x12\x42oltz2BatchRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x16\n\x0eprotein_pdb_id\x18\x02 \x01(\t\x12\x15\n\rligand_smiles\x18\x03 \x03(\t\x12\x15\n\rensemble_size\x18\x04 \x01(\x05\x12\x1c\n\x14use_triton_inference\x18\x05 \x01(\x08\"\x85\x01\n\x13\x42oltz2BatchResponse\x12\x16\n\x0eprotein_pdb_id\x18\x01 \x01(\t\x12\x42\n\naffinities\x18\x02 \x03(\x0b\x32..moleculeforge.v1.oracle.Boltz2BindingAffinity\x12\x12\n\nelapsed_ms\x18\x03 \x01(\x03\x32}\n\rBoltz2Service\x12l\n\x0fPredictAffinity\x12+.moleculeforge.v1.oracle.Boltz2BatchRequest\x1a,.moleculeforge.v1.oracle.Boltz2BatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.oracle.boltz2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOLTZ2BINDINGAFFINITY']._serialized_start=66
  _globals['_BOLTZ2BINDINGAFFINITY']._serialized_end=267
  _globals['_BOLTZ2BATCHREQUEST']._serialized_start=270
  _globals['_BOLTZ2BATCHREQUEST']._serialized_end=410
  _globals['_BOLTZ2BATCHRESPONSE']._serialized_start=413
  _globals['_BOLTZ2BATCHRESPONSE']._serialized_end=546
  _globals['_BOLTZ2SERVICE']._serialized_start=548
  _globals['_BOLTZ2SERVICE']._serialized_end=673
# @@protoc_insertion_point(module_scope)
