# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mf_core.proto_gen.moleculeforge.v1.oracle import fep_pb2 as moleculeforge_dot_v1_dot_oracle_dot_fep__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in moleculeforge/v1/oracle/fep_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FEPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunFEP = channel.unary_unary(
                '/moleculeforge.v1.oracle.FEPService/RunFEP',
                request_serializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchResponse.FromString,
                _registered_method=True)
        self.SubmitFEP = channel.unary_unary(
                '/moleculeforge.v1.oracle.FEPService/SubmitFEP',
                request_serializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatus.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/moleculeforge.v1.oracle.FEPService/GetStatus',
                request_serializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatusRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatus.FromString,
                _registered_method=True)


class FEPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunFEP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def SubmitFEP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')


def add_FEPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunFEP': grpc.unary_unary_rpc_method_handler(
                    servicer.RunFEP,
                    request_deserializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchResponse.SerializeToString,
            ),
            'SubmitFEP': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFEP,
                    request_deserializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatus.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatusRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moleculeforge.v1.oracle.FEPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moleculeforge.v1.oracle.FEPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FEPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunFEP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.oracle.FEPService/RunFEP',
            moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchRequest.SerializeToString,
            moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitFEP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.oracle.FEPService/SubmitFEP',
            moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPBatchRequest.SerializeToString,
            moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.oracle.FEPService/GetStatus',
            moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatusRequest.SerializeToString,
            moleculeforge_dot_v1_dot_oracle_dot_fep__pb2.FEPJobStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
