# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/oracle/fep.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/oracle/fep.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!moleculeforge/v1/oracle/fep.proto\x12\x17moleculeforge.v1.oracle\"\xa5\x02\n\tFEPResult\x12\x17\n\x0fligand_a_smiles\x18\x01 \x01(\t\x12\x17\n\x0fligand_b_smiles\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x64g_kcal_mol\x18\x03 \x01(\x01\x12\x17\n\x0f\x64\x64g_uncertainty\x18\x04 \x01(\x01\x12\x11\n\tn_repeats\x18\x05 \x01(\x05\x12\x0e\n\x06method\x18\x06 \x01(\t\x12L\n\x0eper_repeat_ddg\x18\x07 \x03(\x0b\x32\x34.moleculeforge.v1.oracle.FEPResult.PerRepeatDdgEntry\x12\x11\n\tconverged\x18\x08 \x01(\x08\x1a\x33\n\x11PerRepeatDdgEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x9d\x01\n\x0f\x46\x45PBatchRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x16\n\x0eprotein_pdb_id\x18\x02 \x01(\t\x12\x1f\n\x17reference_ligand_smiles\x18\x03 \x01(\t\x12\x1a\n\x12test_ligand_smiles\x18\x04 \x03(\t\x12\x0e\n\x06method\x18\x05 \x01(\t\x12\x11\n\tn_repeats\x18\x06 \x01(\x05\"s\n\x10\x46\x45PBatchResponse\x12\x33\n\x07results\x18\x01 \x03(\x0b\x32\".moleculeforge.v1.oracle.FEPResult\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x18\n\x10total_elapsed_ms\x18\x03 \x01(\x03\"%\n\x13\x46\x45PJobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\xc2\x01\n\x0c\x46\x45PJobStatus\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12;\n\x08response\x18\x03 \x01(\x0b\x32).moleculeforge.v1.oracle.FEPBatchResponse\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x17\n\x0fsubmitted_at_ms\x18\x05 \x01(\x03\x12\x15\n\rstarted_at_ms\x18\x06 \x01(\x03\x12\x17\n\x0f\x63ompleted_at_ms\x18\x07 \x01(\x03\x32\xab\x02\n\nFEPService\x12]\n\x06RunFEP\x12(.moleculeforge.v1.oracle.FEPBatchRequest\x1a).moleculeforge.v1.oracle.FEPBatchResponse\x12\\\n\tSubmitFEP\x12(.moleculeforge.v1.oracle.FEPBatchRequest\x1a%.moleculeforge.v1.oracle.FEPJobStatus\x12`\n\tGetStatus\x12,.moleculeforge.v1.oracle.FEPJobStatusRequest\x1a%.moleculeforge.v1.oracle.FEPJobStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.oracle.fep_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEPRESULT_PERREPEATDDGENTRY']._loaded_options = None
  _globals['_FEPRESULT_PERREPEATDDGENTRY']._serialized_options = b'8\001'
  _globals['_FEPRESULT']._serialized_start=63
  _globals['_FEPRESULT']._serialized_end=356
  _globals['_FEPRESULT_PERREPEATDDGENTRY']._serialized_start=305
  _globals['_FEPRESULT_PERREPEATDDGENTRY']._serialized_end=356
  _globals['_FEPBATCHREQUEST']._serialized_start=359
  _globals['_FEPBATCHREQUEST']._serialized_end=516
  _globals['_FEPBATCHRESPONSE']._serialized_start=518
  _globals['_FEPBATCHRESPONSE']._serialized_end=633
  _globals['_FEPJOBSTATUSREQUEST']._serialized_start=635
  _globals['_FEPJOBSTATUSREQUEST']._serialized_end=672
  _globals['_FEPJOBSTATUS']._serialized_start=675
  _globals['_FEPJOBSTATUS']._serialized_end=869
  _globals['_FEPSERVICE']._serialized_start=872
  _globals['_FEPSERVICE']._serialized_end=1171
# @@protoc_insertion_point(module_scope)
