# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mf_core.proto_gen.moleculeforge.v1.oracle import oracle_pb2 as moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in moleculeforge/v1/oracle/oracle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OracleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/moleculeforge.v1.oracle.OracleService/Evaluate',
                request_serializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.FromString,
                _registered_method=True)
        self.PredictWithUncertainty = channel.unary_unary(
                '/moleculeforge.v1.oracle.OracleService/PredictWithUncertainty',
                request_serializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.FromString,
                _registered_method=True)
        self.StreamEvaluate = channel.stream_stream(
                '/moleculeforge.v1.oracle.OracleService/StreamEvaluate',
                request_serializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.SerializeToString,
                response_deserializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.FromString,
                _registered_method=True)


class OracleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def PredictWithUncertainty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')

    def StreamEvaluate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise RuntimeError('Method not implemented!')


def add_OracleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.SerializeToString,
            ),
            'PredictWithUncertainty': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictWithUncertainty,
                    request_deserializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.SerializeToString,
            ),
            'StreamEvaluate': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEvaluate,
                    request_deserializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.FromString,
                    response_serializer=moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moleculeforge.v1.oracle.OracleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moleculeforge.v1.oracle.OracleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OracleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.oracle.OracleService/Evaluate',
            moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.SerializeToString,
            moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictWithUncertainty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moleculeforge.v1.oracle.OracleService/PredictWithUncertainty',
            moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.SerializeToString,
            moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvaluate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/moleculeforge.v1.oracle.OracleService/StreamEvaluate',
            moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchRequest.SerializeToString,
            moleculeforge_dot_v1_dot_oracle_dot_oracle__pb2.OracleBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
