# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/retrosyn/retrosyn.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/retrosyn/retrosyn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(moleculeforge/v1/retrosyn/retrosyn.proto\x12\x19moleculeforge.v1.retrosyn\"\xc9\x02\n\x15RetrosynthesisRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x17\n\x0fmolecule_smiles\x18\x02 \x01(\t\x12\x12\n\nmax_routes\x18\x03 \x01(\x05\x12\x11\n\tmax_depth\x18\x04 \x01(\x05\x12\x0e\n\x06\x65ngine\x18\x05 \x01(\t\x12\x1f\n\x17include_building_blocks\x18\x06 \x01(\x08\x12\x1b\n\x13price_threshold_usd\x18\x07 \x01(\x01\x12Y\n\rengine_params\x18\x08 \x03(\x0b\x32\x42.moleculeforge.v1.retrosyn.RetrosynthesisRequest.EngineParamsEntry\x1a\x33\n\x11\x45ngineParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x97\x01\n\x16RetrosynthesisResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x39\n\x06routes\x18\x02 \x03(\x0b\x32).moleculeforge.v1.retrosyn.SyntheticRoute\x12\x1a\n\x12total_routes_found\x18\x03 \x01(\x05\x12\x12\n\nelapsed_ms\x18\x04 \x01(\x03\"\xdd\x01\n\x0eSyntheticRoute\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x17\n\x0freaction_smiles\x18\x02 \x03(\t\x12\x17\n\x0fpredicted_score\x18\x03 \x01(\x01\x12\x17\n\x0fpredicted_yield\x18\x04 \x01(\x01\x12\x0f\n\x07n_steps\x18\x05 \x01(\x05\x12\x17\n\x0f\x62uilding_blocks\x18\x06 \x03(\t\x12 \n\x18\x65stimated_cost_usd_per_g\x18\x07 \x01(\x01\x12\"\n\x1a\x61ll_commercially_available\x18\x08 \x01(\x08\x32\x81\x02\n\x0fRetrosynService\x12q\n\nFindRoutes\x12\x30.moleculeforge.v1.retrosyn.RetrosynthesisRequest\x1a\x31.moleculeforge.v1.retrosyn.RetrosynthesisResponse\x12{\n\x10\x46indRoutesStream\x12\x30.moleculeforge.v1.retrosyn.RetrosynthesisRequest\x1a\x31.moleculeforge.v1.retrosyn.RetrosynthesisResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.retrosyn.retrosyn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETROSYNTHESISREQUEST_ENGINEPARAMSENTRY']._loaded_options = None
  _globals['_RETROSYNTHESISREQUEST_ENGINEPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_RETROSYNTHESISREQUEST']._serialized_start=72
  _globals['_RETROSYNTHESISREQUEST']._serialized_end=401
  _globals['_RETROSYNTHESISREQUEST_ENGINEPARAMSENTRY']._serialized_start=350
  _globals['_RETROSYNTHESISREQUEST_ENGINEPARAMSENTRY']._serialized_end=401
  _globals['_RETROSYNTHESISRESPONSE']._serialized_start=404
  _globals['_RETROSYNTHESISRESPONSE']._serialized_end=555
  _globals['_SYNTHETICROUTE']._serialized_start=558
  _globals['_SYNTHETICROUTE']._serialized_end=779
  _globals['_RETROSYNSERVICE']._serialized_start=782
  _globals['_RETROSYNSERVICE']._serialized_end=1039
# @@protoc_insertion_point(module_scope)
