# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moleculeforge/v1/retrosyn/route.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moleculeforge/v1/retrosyn/route.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%moleculeforge/v1/retrosyn/route.proto\x12\x19moleculeforge.v1.retrosyn\"a\n\rRouteEncoding\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x16\n\x0ehumu_embedding\x18\x02 \x01(\x0c\x12\x11\n\tcurvature\x18\x03 \x01(\x01\x12\x13\n\x0bpath_length\x18\x04 \x01(\x05\"\x8a\x01\n\x15RouteComparisonResult\x12\x12\n\nroute_a_id\x18\x01 \x01(\t\x12\x12\n\nroute_b_id\x18\x02 \x01(\t\x12\x19\n\x11geodesic_distance\x18\x03 \x01(\x01\x12\x12\n\nsimilarity\x18\x04 \x01(\x01\x12\x1a\n\x12\x64istance_breakdown\x18\x05 \x03(\x01\"q\n\x0cRouteCluster\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12\x11\n\troute_ids\x18\x02 \x03(\t\x12\x1a\n\x12\x63\x65ntroid_embedding\x18\x03 \x01(\x0c\x12\x1e\n\x16intra_cluster_distance\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moleculeforge.v1.retrosyn.route_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEENCODING']._serialized_start=68
  _globals['_ROUTEENCODING']._serialized_end=165
  _globals['_ROUTECOMPARISONRESULT']._serialized_start=168
  _globals['_ROUTECOMPARISONRESULT']._serialized_end=306
  _globals['_ROUTECLUSTER']._serialized_start=308
  _globals['_ROUTECLUSTER']._serialized_end=421
# @@protoc_insertion_point(module_scope)
